apiVersion: v1
kind: Service
metadata:  
    name: test-Service
    deletionGracePeriodSeconds: 2.0 
    namespace: test-namespace 
spec:
    allocateLoadBalancerNodePorts: false
    clusterIP: emptyString
    clusterIPs:
      - 10.0.0.0
    externalIPs:
      - 192.168.1.1
    externalTrafficPolicy: Local
    healthCheckNodePort: 5
    internalTrafficPolicy: Cluster
    ipFamilies: 
      - IPv4
    ipFamilyPolicy: RequireDualStack
    loadBalancerClass: example.com/internal-vip
    ports:
      - port: 3662
        name: portname
        protocol: SCTP
        nodePort: 2923
        targetPort: 2342
        appProtocol: kubernetes.io/h2c
    publishNotReadyAddresses: true
    selector:
      app: my-app
      tier: frontend
    sessionAffinity: ClientIP
    sessionAffinityConfig: 
      clientIP:
        timeoutSeconds: 10800
    trafficDistribution: PreferClose
    Type: LoadBalancer 
